### PR TITLE
Rename +xml to +db

### PR DESCRIPTION
**Pull request by hagenw**
I'm still not happy about the slightly confusing wording for using the data base, e.g. `xml.dbTmp` so I changed it to `db.tmp()` instead and for all the other functions, too.

I know that this will have huge consequences for all other parts of Two!Ears, but in the long run it should be more user friendly.

### CODE REVIEW

**Comment by fietew** [comment]
Not all functions that you changed are related to the database:
* MetaObject.m
* PropertyDescription.m
* OpenXML.m
* Validate.m
* tef.xsd
* tef.xsl

I think the better solution would be to put this files into the +xml directory and adjust the function calls accordingly.

**Comment by hagenw** [comment]
That's a good point, I have split it now into `+db` and `+xml`

**Comment by fietew** [comment]
So shall we merge this now, this I will change quite a bit for other users?

**Comment by hagenw** [comment]
I would prefer to merge it. But before you do it, we should create corresponding branches in all related repositories where we also do the changes. Or was your plan to just announce it to the WP3 guys?

**Comment by fietew** [comment]
Imho, an announcement would be sufficied.

**Comment by hagenw** [comment]
Ok, but we should change it in the documentation of the binaural simulator.

**Comment by fietew** [comment]
There is now a branch https://github.com/TWOEARS/documentation/tree/db

I used this script to replace the function calls
```
#!/bin/bash
# this is a script to replace anything

grep -rl 'xml.dbClearTmp' $1 | xargs sed -i 's/xml.dbClearTmp/db.clearTmp/g'
grep -rl 'xml.dbDownloadFile' $1 | xargs sed -i 's/xml.dbDownloadFile/db.downloadFile/g'
grep -rl 'xml.dbGetFile' $1 | xargs sed -i 's/xml.dbGetFile/db.getFile/g'
grep -rl 'xml.dbPath' $1 | xargs sed -i 's/xml.dbPath/db.path/g'
grep -rl 'xml.dbTmp' $1 | xargs sed -i 's/xml.dbTmp/db.tmp/g'
grep -rl 'xml.dbURL' $1 | xargs sed -i 's/xml.dbURL/db.url/g'
grep -rl 'xml.dbOpenXML' $1 | xargs sed -i 's/xml.dbOpenXML/xml.openXML/g'
grep -rl 'xml.dbValidate' $1 | xargs sed -i 's/xml.dbValidate/xml.validate/g'
```

I will provide the script to the others. Do you think, that we should change ``xml.openXML`` to ``xml.open``?

**Comment by hagenw** [comment]
Yes, `xml.open` seems to be a good idea.

**Comment by hagenw** [comment]
Ok, I merged the documentation.

**Pull request merged**
