### PR TITLE
Add functions for standalone handling of SOFA files

### PR DESCRIPTION
**Pull request by hagenw**
Hi @fietew.

We have a new repo, hosting the training stages for the localisation knowledge sources, see [TWOEARS/localisation-training-pipeline](/TWOEARS/localisation-training-pipeline).
During the training process we need to generate a lot of different binaural signals for which only the apparent direction of the source matters (seen from the point of the listener). As I was not sure how to implement this using the existing Binaural Simulator and as no block processing is needed I created the functions that are part of this pull request and can be used to get the desired impulse responses directly from a SOFA file.

For example, in order to get an impulse response for a source at `azimuth` from the listener point of view all you have to do is the following:
```Matlab
brir = sofaGetImpulseResponse(sofaStructOrFile, azimuth);
```
This works for the `SimpleFreeFieldHRIR` and `MultiSpeakerBRIR` convention.

It would be nice, if you could tackle the following things:

- [ ] Convert all BRIR data sets to the `MultiSpeakerBRIR` convention.
- [ ] Review the [cleanup branch of localisation-training-pipeline](/TWOEARS/localisation-training-pipeline/tree/cleanup) and see if the HRTF processing can be done in a better way using maybe directly the Binaural Simulator (see for example [here](/TWOEARS/localisation-training-pipeline/blob/cleanup/f1_createBinauralFeatureTrain.m#L56), [here](/TWOEARS/localisation-training-pipeline/blob/cleanup/f1_createBinauralFeatureTrain.m#L180), and [here](/TWOEARS/localisation-training-pipeline/blob/cleanup/f1_createBinauralFeatureTrain.m#L249)).
- [ ] Decide if this pull request is then needed or not.
- [ ] Help @ryanckim and @ningma97 to clean up the HRTF related code accordingly.

### CODE REVIEW

**Comment by fietew** [comment]
I think, we should stick to the package system matlab provides. Please change the directory from ``sofa`` to ``+sofa`` and remove the ``sofa``-prefix from all the *.m files inside that directory.

**Comment by fietew** [comment]
Is there any reason behind not supporting the SingleRoomDRIR convention of SOFA?

**Comment by fietew** [comment]
The following things have to added to the implementation imho:
- [ ] allow ``azimuth`` to be a vector of desired angles for ``sofaGetImpulseResponse``
- [ ] loading each impulse response separately from the hard disk is rather slow. Enable segment-wise loading, see e.g. https://github.com/TWOEARS/binaural-simulator/blob/master/src/%2Bsimulator/DirectionalIR.m#L208-L226
- [ ] the implementation ignores possible non-zero elevation. This may lead to undesired results for 3D HRTF/BRTF datasets, which are in our database. Something similar to this https://github.com/TWOEARS/binaural-simulator/blob/master/src/%2Bsimulator/DirectionalIR.m#L197
- [ ] return the sample rate of the impulse responses as an additional output parameter

**Comment by fietew** [comment]
Regarding the Open Points:

> Convert all BRIR data sets to the MultiSpeakerBRIR convention.

I think we should leave them in the SingleRoomDRIR format and rather support the format in the API

> Review the cleanup branch of localisation-training-pipeline and see if the HRTF processing can be done in a better way using maybe directly the Binaural Simulator (see for example here, here, and here).

I think the code could be improved by allowing the ``azimuth`` to be a vector

> Decide if this pull request is then needed or not.

It is indeed an improvement of the code

> Help @ryanckim and @ningma97 to clean up the HRTF related code accordingly.

at the moment I see no need for improvement with the current API

**Comment by fietew** [comment]
Fixed it, hopefully

**Comment by hagenw** [comment]
Yes, now it works for me.

**Comment by hagenw** [comment]
The case of non-zero elevation is still missing and I'm not completely sure, what to do with it.

One solution would be as you proposed to ensure that the elevation is near 0° or to add the option to specify `elevation` as an parameter to `getImpulseResponse()`. In both cases we would have to add a little bit of code, as you have to take the relative positions of the loudspeakers to the listener into account.

As I have not the enough time to do it at the moment, should we postpone it and merge this as it is, or have you time to implement it?

**Comment by fietew** [comment]
yes, we can postpone that

**Comment by hagenw** [comment]
OK, can you create an issue for the elevation case please, and then merge this pull request.

**Pull request merged**
