### PR TITLE
implement new RobotInterface

### PR DESCRIPTION
**Pull request by fietew**
@TWOEARS/all:
As long as you don't use the new functionalities of the Interface, nothing should change in the behaviour of the Interface.

@ningma97:
Could you please check, if the "Robot" behaves like you would expect it?

### CODE REVIEW

**Comment by ningma97** [comment]
I've made the change to the interfaces related to Head Orientation: from the 270/right convention to the -90/right convention. 

@fietew is it a problem for your simulator?

**Comment by kashefy** [comment]
@ningma97, I'm unfamiliar with the conventions, could you briefly explain what each convention is?

**Comment by ningma97** [comment]
Will forward the email exchanges to you

**Comment by fietew** [comment]
ToDo's:

- [x] @ningma97  to update RobotInterface.m
- [ ] @fietew to update the simulator (subclass of RobotInterface)
- [ ] @ningma97 to test the updated simulator and merge this into the master branch once tested
- [ ] @ningma97 to update JidoInterface.m to be tested when @Bcl-Isir is in Toulouse.

**Comment by ningma97** [comment]
@fietew In SimulatorConvexRoom.m  AzimuthMax and AzimuthMin are defined. It is not clear what they represent. Presumedly AzimuthMax is the maximum azimuth to turn the head right, and AzimuthMin is the maximum azimuth to turn the head left (negative)?

**Comment by fietew** [comment]
@ningma97 In the current implementation of the binaural simulator turning the head or turning the torso are equivalent as the underlying BRIR dataset does not distinguish between the two cases. However, for our Toulouse measurement we have not measured the full circle of orientations at each position. Now, the question is, how to handle head/torso turnings, which result in orientation which are out of bounce. 

- Option 1: We can use a simple nearest-neighbor strategy, where the "outer" measurements would be repeated in order to fill the full circle
- Option 2: We do not permit such turnings. This is however not very intuitive for the user, as the range of existing orientations (in world coordinates) changes at each position of our dataset, since we oriented the KEMAR differently at each position.

Any other ideas?

**Comment by hagenw** [comment]
I'm afraid your first solution has severe consequences for the evaluation of some of our models. For example assume you would to test the `DnnLocationKS` using head movements. Then it is very likely that the head is turned to a position where we don't have the actual measurement and it is filled by the nearest measurement. This will lead to wrong direction estimates.
For such an evaluation it seems to be much more sensitive to set head turning boundaries before and the `RotationKS` has then choose an intelligent turning strategy incorporating those boundaries.

This could also mean that we could hide it from the user to some extend.

**Comment by ningma97** [comment]
I am modifying RotationKS to take into account the possible head turning boundaries so that we don't turn the head out of the limits. This means it needs to use the head-to-torso orientation and AzimuthMax and AzimuthMin, but it's not very clear what the two variables represent, thus my original question.

Perhaps call them maxHeadHead and maxHeadRight?

**Comment by fietew** [comment]
Specifying a maximum left/right head-above-torso orientation does only ensure non-out-of-bounds (world coordinate) orientations, if the torso orientation is exactly the "middle" of the available (world coordinate) orientations. Is that the behaviour, you want to be implemented?

**Comment by fietew** [comment]
AzimuthMax and AzimuthMin define the range of (world coordinate) orientations, which are available in the BRIR dataset.

**Comment by ningma97** [comment]
For simulation I would only set the torso orientation to the available ones, e.g. To initialise the robot:
 sim.moveRobot(0, 0, 90, 'absolute');
 sim.rotateHead(0, 'absolute');

Once both the torso and head face the centre line, then only rotate the head afterward.

For Jido we are fine as long as we make sure the head-to-torso is valid

**Comment by ningma97** [comment]
@fietew ok thanks. We need to add another method to the interface perhaps 

    getHeadTurnLimits() which returns the maximum head turn angles relative to the torso? In my view anything related to the head turning should be in the frame of torso, and only torso position should be in the world frame. Makes sense?

**Comment by hagenw** [comment]
This sounds like a solution, but it would need good documentation or maybe even better a fix restriction in `sim.moveRobot` so that the robot is only allowed to turn its direction towards 0°?
Otherwise the problem still exists.

**Comment by fietew** [comment]
@hagenw Could you please specify, what exactly "the robot turns" means in your sentence? Does the torso or the head turn?

**Comment by hagenw** [comment]
I mean what is turned by `sim.moveRobot` from @ningma97 example. I assumed that the torso was ment by this.

**Comment by fietew** [comment]
Okay. Is the 0° degree in you statement 
> the robot is only allowed to turn its direction towards 0°" 

defined in world coordinates?

**Comment by hagenw** [comment]
Yes, I thought this was the solution by @ningma97. Turn the robot torso always to 0° in world coordinates and then use the head rotations. This would ensure that the head coordinate system is identical to the world coordinate system for head rotations.

**Comment by fietew** [comment]
Hmm, I'm still not sure, if we are all on the same page. Our Toulouse dataset has 4 measurement position with 4 different torso orientations. I don't see, how setting the torso orientation to 0° has anything to do with the torso orientations of the measurements.

**Comment by ningma97** [comment]
Sorry I don't remember the torso orientations we used in the Toulouse BRIRs, but essentially
```
worldX = 0; worldY = 0, worldTheta = 90;
sim.moveRobot(worldX, worldY, worldTheta, 'absolute');
sim.rotateHead(0, 'absolute');
```
The initial torso position will be set according to the BRIRs specification, and the initial head orientation is always 0 deg relative to the torso. Makes sense?

**Comment by fietew** [comment]
By 'will be set' you mean, that the user has to set it or is this done automatically?

**Comment by hagenw** [comment]
"The user has to set" will never work. This was my only concern, we should make sure that this works automatically. How exactly, I don't care ;)

**Comment by fietew** [comment]
But the actual problem is exactly the "How", if we want to support BRIR datasets with multiple listening positions, which have different torso orientations.

**Comment by ningma97** [comment]
Is there a way to figure out the Torso position from the BRIR dataset? If so we should automatically set the robot to the default position when a BRIR set is loaded into the Simulator. Then in the moveRobot() method throws an exception if it's an invalid "move" request.

I guess most BRIRs (like the TU Berlin ones) have only one listening position which is 90-deg in the world frame?

rotateHead() should always set head orientation relative to the torso position, and we need to know maxLeft and maxRight of head rotation for the torso position.

Let me know if you want to have a Skype chat. Might be quicker to sort this out.

**Comment by fietew** [comment]
I uploaded a new test function under ''test/test_toulouse.m''. The behaviour of the simulator is now the following: Depending on the current position of the KEMAR, the current torso orientation is compared with the one available in the dataset. If these orientations differ, a warning is given and the torso orientation is automatically corrected to the one in the data. Head-above-torso rotations, which are out of bounds result in an error.

**Comment by ningma97** [comment]
I've tested this extensively and it works great. Will merge this into master.

**Pull request merged**
